name: Release tool_f

on:
  push:
    tags:
      - 'tool_f/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build
        run: |
          cd tool_f
          go build -ldflags="-w -s" -trimpath -o bin/tool_f cmd/tool_f/main.go
          cd bin
          gzip tool_f
      - name: Queries the GitHub actions runner's public IP address
        id: ip
        uses: haythem/public-ip@bdddd92c198b0955f0b494a8ebeac529754262ff # v1.3.0
      - name: Set up Azure CLI
        uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2 # v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Add the public IP to the whitelist
        # uses: azure/CLI@fa0f960f00db49b95fdb54328a767aee31e80105 # v1.0.7
        # with:
        #   inlineScript: |
        #     az storage account network-rule add \
        #       --account-name ${{ secrets.AZURE_SA_NAME }} \
        #       --ip-address ${{ steps.ip.outputs.ipv4 }}
        run: |
          az storage account network-rule add \
            --account-name ${{ secrets.AZURE_SA_NAME }} \
            --ip-address ${{ steps.ip.outputs.ipv4 }}
      - name: Sleep for 15 seconds
        run: sleep 15s
        shell: bash
      - name: Upload to blob storage
        uses: azure/CLI@fa0f960f00db49b95fdb54328a767aee31e80105 # v1.0.7
        with:
          inlineScript: |
            az storage blob upload-batch \
              --connection-string "${{ secrets.ConnectionString }}" \
              --source ./tool_f/bin \
              --destination 'release' \
              --overwrite true \
              --pattern *.gz
      - name: Remove the public IP from the whitelist
        if: always()
        uses: azure/CLI@fa0f960f00db49b95fdb54328a767aee31e80105 # v1.0.7
        with:
          inlineScript: |
            az storage account network-rule remove \
              --account-name ${{ secrets.AZURE_SA_NAME }} \
              --ip-address ${{ steps.ip.outputs.ipv4 }}
      - name: logout
        run: |
          az logout
        if: always()
