name: Release tool_c

on:
  push:
    tags:
      - 'tool_c/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Cross build
        run: |
          cd tool_c
          make cross

      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - name: Upload
        run: |
          cd tool_c
          make upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
