name: Release tool_f

on:
  push:
    tags:
      - 'tool_f/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build
        run: |
          cd tool_f
          go build -ldflags="-w -s" -trimpath -o bin/tool_f cmd/tool_f/main.go
          cd bin
          gzip tool_f
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: ./tool_f/bin
          container_name: '$web'
          connection_string: ${{ secrets.ConnectionString }}
          extra_args: '--pattern *.gz'
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: 'true'
      # - name: Set up Azure CLI
      #   uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2 # v1.4.6
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - name: Upload to blob storage
      #   uses: azure/CLI@fa0f960f00db49b95fdb54328a767aee31e80105 # v1.0.7
      #   with:
      #     inlineScript: |
      #       az storage blob upload-batch \
      #         --account-name ${{ secrets.AZURE_SA_NAME }} \
      #         --destination '$web' \
      #         --source ./tool_f
      # - name: logout
      #   run: |
      #     az logout
      #   if: always()
